allowBuilds:
  "@percy/core": true
  core-js: false
  protobufjs: false
  unrs-resolver: false

autoInstallPeers: false

minimumReleaseAge: 720

minimumReleaseAgeExclude:
  - "@codemod-utils/*"
  - "@ijlee2-frontend-configs/*"
  - '@changesets/get-github-info@1.0.0'
  - globals@17.10.0

overrides:
  ember-cli-htmlbars: ^7.0.1

packages:
  - "configs/**"
  - "docs-app"
  - "packages/ember-container-query"
  - "test-app"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
  - "*stylelint*"

resolvePeersFromWorkspaceRoot: false

verifyDepsBeforeRun: "warn"
