allowBuilds:
  "@percy/core": true
  "@percy/ember@https://codeload.github.com/ijlee2/percy-ember/tar.gz/c42f9793a99386edca27496194e94b8e07a17e73": true
  core-js: false
  protobufjs: false
  unrs-resolver: false

autoDedupe: true

autoInstallPeers: false

minimumReleaseAge: 720

minimumReleaseAgeExclude:
  - "@codemod-utils/*"
  - "@ijlee2-frontend-configs/*"
  - "ember-testem"

packages:
  - "configs/**"
  - "docs-app"
  - "packages/ember-container-query"
  - "test-app"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
  - "*stylelint*"

resolvePeersFromWorkspaceRoot: false

verifyDepsBeforeRun: "warn"
